### ISSUE TITLE
/bin/bash: line 3: file.exe: command not found

### ISSUE THREAD

**Issue by ShockwaveNN** [nscaife/file-windows#2]
Hi there, I trying to compile `file` for windows on my ubuntu and I try your script.
But it give me error
`/bin/bash: line 3: file.exe: command not found` on [this line](https://github.com/nscaife/file-windows/blob/master/build.sh#L17)
Any idea that it can be?

**Comment by nscaife** [comment]
Hi, the readme indicates that you will receive this error on build.  If expected output files are present, the build was successful.

**Comment by ShockwaveNN** [comment]
oh, sorry, my bad. Your project pretty straigh-forward and I didn't look to readme :)
