### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by mattsmacs** [nscaife/file-windows#5]
As you can see below it only creates the libgnurx-0.dll and not the others.

x86_64-w64-mingw32-gcc -mthreads -shared -o libgnurx-0.dll -Wl,--enable-auto-image-base -Wl,--out-implib,libgnurx.dll.a -Wl,--output-def,libgnurx.def regex.o
cp -p libgnurx.dll.a libregex.a
./build.sh: line 11: autoreconf: command not found
./build.sh: line 12: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat 'magic/magic.mgc': No such file or directory
make: *** No rule to make target 'clean'.  Stop.
./build.sh: line 16: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat 'src/.libs/libmagic-1.dll': No such file or directory
cp: cannot stat 'src/.libs/file.exe': No such file or directory
mattsmacs@Pentest1:~/file-windows$ cd dist
mattsmacs@Pentest1:~/file-windows/dist$ ls
COPYING.file  COPYING.libgnurx  libgnurx-0.dll

**Comment by mattsmacs** [comment]
Btw this was done using an Ubuntu bash shell on a Windows 10 machine

**Comment by nscaife** [comment]
> ./build.sh: line 11: autoreconf: command not found

Did you install the prerequisites from the readme?

**Comment by mattsmacs** [comment]
Yes

**Comment by mattsmacs** [comment]
I just ran through everything again and same result

**Comment by mattsmacs** [comment]
Has something in the files been changed?
